name: "Report"
description: "Run tests & comment coverage on pull request"
inputs:
  GITHUB_TOKEN:
    description: "The GITHUB_TOKEN secret"
    required: true
    default: ${{ github.token }}
  command:
    description: "Command to run the tests"
    required: true

runs:
  using: "node12"
  main: "build/main.js"
